### ISSUE TITLE
fmm - does not work

### ISSUE THREAD

**Issue by flameSla** [suisseWalter/factorio-benchmark#19]
for **fmm**, you need the **"mods"** folder and the **"mod-list.json"**, **"mod-settings.dat"** files

`unable to read mod directory: invalid mods directory: "factorio\\mods"`

**Comment by suisseWalter** [comment]
Has this always been like this? Or has it changed with the introduction of the config file?
Does it work if you put 
mods_dir="Factorio\mods" into the config file?(or add as command line parameter in the call function)?
Also a mod-list.json should be there right?
For the mod-settings.dat file, we probably have to ship one and copy it on init.(or can it be completely empty?)

**Comment by flameSla** [comment]
It's always been like this
1) download the sources to a new folder, you will have a clean installation without Factorio
2) python3 benchmarker.py -u -m
3) Factorio will be downloaded, but there will be no mods folder and files, and this error will be constantly

**Comment by flameSla** [comment]
I have already written a fix

**Comment by flameSla** [comment]
https://github.com/flameSla/factorio-benchmark/commit/d33719adb95dadf281cb4fe4daceab3debe7c542
just need to remove all errors when merging

**Comment by flameSla** [comment]
I still haven't figured out how to create a "mod-settings.dat" file
I copied the file from my "multiplayer" game, I hope there will be no problems due to the incorrect "mod-settings.dat" ("mod-settings.dat" does not match the file "mod-list.json")
